apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: backstage-test-app
  description: Example entity in backstage app
  tags:
    - go
    - website
spec:
  type: service
  lifecycle: production
  owner: cdvillard